In [ ]:
import numpy as np

Step 1 : Create

In [ ]:
one_d_arr = np.arange(1,11)
print(one_d_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
two_d_arr = np.arange(1,10)
two_d_arr = two_d_arr.reshape(3,3)
print(two_d_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Step 2 : Display

In [ ]:
one_d_arr.ndim

1

In [ ]:
one_d_arr.shape

(10,)

In [ ]:
one_d_arr.size

10

In [ ]:
one_d_arr.itemsize

8

In [ ]:
two_d_arr.ndim

2

In [ ]:
two_d_arr.shape

(3, 3)

In [ ]:
two_d_arr.size

9

In [ ]:
two_d_arr.itemsize

8

Step 3 :

In [ ]:
Arr = np.array([[1.2,3.6,8.9],
[2.4,5.7,7.5],
[3.4,6.0,7.1]])
print("Float Array:")
print(Arr)
int_arr = Arr.astype(int)
print("Integer Array:")
print(int_arr)

Float Array:
[[1.2 3.6 8.9]
 [2.4 5.7 7.5]
 [3.4 6.  7.1]]
Integer Array:
[[1 3 8]
 [2 5 7]
 [3 6 7]]
