In [33]:
import numpy as np

**PART** ***1***

In [34]:
A = np.arange(1,13)
B = mat.reshape(3,4)
C = mat.reshape(2,6)
print("Matrix A:\n",A)
print("\nMatrix A in 3x4:\n",B)
print("\nMatrix A in 2x6:\n",C)

Matrix A:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Matrix A in 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix A in 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**PART** ***2***

In [35]:
A = np.array([[1,2,3],[4,5,6]])
fl = A.flatten()
rv = A.ravel()
print("Matrix A:\n",A)
print("\nFlatten Matrix A:\n",fl)
print("\nRavel Matrix A:\n",rv)

Matrix A:
 [[1 2 3]
 [4 5 6]]

Flatten Matrix A:
 [1 2 3 4 5 6]

Ravel Matrix A:
 [1 2 3 4 5 6]


In [36]:
fl[0] = 99
print("Matrix A:\n",A)
print("\nFlatten Matrix A:\n",fl)

Matrix A:
 [[1 2 3]
 [4 5 6]]

Flatten Matrix A:
 [99  2  3  4  5  6]


In [37]:
rv[1] = 99
print("Matrix A:\n",A)
print("\nRavel Matrix A:\n",rv)


Matrix A:
 [[ 1 99  3]
 [ 4  5  6]]

Ravel Matrix A:
 [ 1 99  3  4  5  6]


**PART** ***3***

In [38]:
arr = np.arange(1,10)
arr = arr.reshape(3,3)
print("Matrix:\n",arr)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
fl = arr.flatten()
print("Flatten Matrix:\n",fl)
rv = arr.ravel()
print("\nRavel Matrix:\n",rv)

Flatten Matrix:
 [1 2 3 4 5 6 7 8 9]

Ravel Matrix:
 [1 2 3 4 5 6 7 8 9]


In [43]:
fl[4] = 804
print("Matrix:\n",arr)
print("\nFlatten Matrix:\n",fl)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatten Matrix:
 [  1   2   3   4 804   6   7   8   9]


In [45]:
rv[4] = 444
print("Matrix:\n",arr)
print("\nRavel Matrix:\n",rv)

Matrix:
 [[  1   2   3]
 [  4 444   6]
 [  7   8   9]]

Ravel Matrix:
 [  1   2   3   4 444   6   7   8   9]
