In [ ]:
import numpy as np

In [ ]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("\nGiven Array:\n", arr)


Given Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [ ]:
# 1. Extract second row
print("\nSecond row:", arr[1])


Second row: [50 60 70 80]


In [ ]:
# 2. Extract first two rows and second two columns:
print(f"First two rows:\n{arr[0]}\n{arr[1]}")
print(f"\nSecond two columns:\n{arr[:,1]}\n{arr[:,2]}")

First two rows:
[10 20 30 40]
[1 2 3 4]

Second two columns:
[ 20   2 100]
[ 30   3 110]


In [ ]:
# 3. Extract the last column using slicing
print("\nLast column:", arr[:, -1])


Last column: [ 40  80 120]


In [ ]:
# 4. Replace the middle row with [1, 2, 3, 4]
arr[1] = [1, 2, 3, 4]
print("\nArray after replacing middle row:\n", arr)


Array after replacing middle row:
 [[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]
