In [ ]:
import numpy as np

In [ ]:
zero_mat = np.zeros((4,4))
print(zero_mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
one_mat = np.ones((3,2))
print(one_mat)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
id_mat = np.eye((5))
print(id_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
mat = np.full((3,3),7)
print(mat)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
Mat = np.random.randint(10,100,(3,4))
print(Mat)

[[63 71 75 13]
 [50 49 12 85]
 [12 67 12 40]]


In [ ]:
Mat = np.arange(5,50,5)
Matt = Mat.reshape(3,3)
print(Matt)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
