In [ ]:
import numpy as np

***PART 1***



In [ ]:
A = np.random.randint(1,25,5)
B = np.random.randint(26,100,5)

In [ ]:
print("MATRIX A:\n",A)
print("MATRIX B:\n",B)

MATRIX A:
 [ 1  2 22  5 23]
MATRIX B:
 [96 71 99 95 31]


In [ ]:
print("Addition of Matrix A and B:\n",A+B)
print("\nSubtraction of Matrix A and B:\n",A-B)
print("\nMultiplication of Matrix A and B:\n",A*B)
print("\nDivision of Matrix A and B:\n",A/B)

Addition of Matrix A and B:
 [ 97  73 121 100  54]

Subtraction of Matrix A and B:
 [-95 -69 -77 -90  -8]

Multiplication of Matrix A and B:
 [  96  142 2178  475  713]

Division of Matrix A and B:
 [0.01041667 0.02816901 0.22222222 0.05263158 0.74193548]


***PART*** ***2***

In [ ]:
X = np.random.randint(1,100,9)
X = X.reshape(3,3)

In [ ]:
Square_Root = np.sqrt(X)
print("Square Root of Matrix X:\n",Square_Root)
Exp = np.exp(X)
print("\nExponential of Matrix X:\n",Exp)
Sin = np.sin(X)
print("\nSin of Matrix X:\n",Sin)

Square Root of Matrix X:
 [[3.31662479 4.12310563 5.09901951]
 [7.61577311 9.89949494 2.23606798]
 [6.40312424 8.77496439 8.88819442]]

Exponential of Matrix X:
 [[5.98741417e+04 2.41549528e+07 1.95729609e+11]
 [1.54553894e+25 3.63797095e+42 1.48413159e+02]
 [6.39843494e+17 2.75851345e+33 2.03828107e+34]]

Sin of Matrix X:
 [[-0.99999021 -0.96139749  0.76255845]
 [ 0.99287265 -0.57338187 -0.95892427]
 [-0.15862267  0.99952016 -0.44411267]]


***PART*** ***3***

In [ ]:
Celsius = np.random.randint(-20,50,10)
fehrenhiet = (Celsius*9/5)+32
print("Celsius:\n",Celsius)
print("\nFehrenhiet:\n",fehrenhiet)


Celsius:
 [  7 -19  33  35  38  39  48   3  16  31]

Fehrenhiet:
 [ 44.6  -2.2  91.4  95.  100.4 102.2 118.4  37.4  60.8  87.8]
