In [ ]:
import numpy as np

In [ ]:
A = np.random.randint(1,100,9)
A = A.reshape(3,3)
print("Martix A:\n",A)

Martix A:
 [[24 49 39]
 [52 47 99]
 [92 71 52]]


In [ ]:
col = np.array([[4],[2],[5]])
row = np.array([1,2,3])
print("Vector column:\n",col)
print("Vector row:\n",row)
print("\nMatrix A\n",A)
print("\nMatrix A + 10:\n", A+10)
print("\nMatrix A + row vector\n", A+row)
print("\nMatrix A + column vector\n", A+col)

Vector column:
 [[4]
 [2]
 [5]]
Vector row:
 [1 2 3]

Matrix A
 [[24 49 39]
 [52 47 99]
 [92 71 52]]

Matrix A + 10:
 [[ 34  59  49]
 [ 62  57 109]
 [102  81  62]]

Matrix A + row vector
 [[ 25  51  42]
 [ 53  49 102]
 [ 93  73  55]]

Matrix A + column vector
 [[ 28  53  43]
 [ 54  49 101]
 [ 97  76  57]]
